### ISSUE TITLE
Running mqlight on OpenShift

### ISSUE THREAD

**Issue by chainhead** [ibm-messaging/mqlight-docker#3]
Going by the instructions to run `mqlight` with Docker, it seems the following are required:
1. `volume` for `/var/mqlight`
2. `env` variable `LICENSE` set to `accept` (provided via `ConfigMap` in YAML below).

So, I created a `Deployment` YAML for the same and submitted. The container keeps crashing without any logs. What am I missing? How do we run this container in OpenShift? I want to run this container for a simple pub-sub demo.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqlight
spec:
  selector:
    matchLabels:
      app: mqlight
  template:
    metadata:
      labels:
        app: mqlight
    spec:
      containers:
        - name: mqlight
          image: ibmcom/mqlight
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: mqlight-config
          volumeMounts:
            - name: mqlight
              mountPath: /var/mqlight
          ports:
          - name: mqlight-amqp
            containerPort: 5672
          - name: mqlight-web-ui
            containerPort: 9180            
      volumes:
        - name: mqlight
          persistentVolumeClaim: 
            claimName: mqlight
```
